[package]
name = "ac97d"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1"
common = { path = "../common" }
log = "0.4"
redox-daemon = "0.1"
redox-log = "0.1"
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.3"
spin = "0.9"
