[package]
name = "bgad"
version = "0.1.0"
edition = "2021"

[dependencies]
orbclient = "0.3.47"
log = "0.4"
redox-daemon = "0.1"
redox-scheme = "0.6.2"
redox_syscall = "0.5"

common = { path = "../../common" }
inputd = { path = "../../inputd" }
pcid = { path = "../../pcid" }
libredox = "0.1.3"
