[package]
name = "e1000d"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1"
netutils = { git = "https://gitlab.redox-os.org/redox-os/netutils.git", branch = "redox-unix" }
redox_event = { git = "https://gitlab.redox-os.org/redox-os/event.git" }
redox_syscall = "0.2.12"
