[package]
name = "xhcid"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "xhcid"
path = "src/main.rs"

[lib]
name = "xhcid_interface"
path = "src/lib.rs"

[dependencies]
bitflags = "1"
chashmap = "2.2.2"
crossbeam-channel = "0.4"
futures = "0.3"
plain = "0.2"
lazy_static = "1.4"
log = "0.4"
redox-daemon = "0.1"
redox_event = "0.4.1"
redox-scheme = "0.6.2"
redox_syscall = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smallvec = { version = "1", features = ["serde"] }
thiserror = "1"
toml = "0.5"

common = { path = "../../common" }
pcid = { path = "../../pcid" }
libredox = "0.1.3"
regex = "1.10.6"
